<?php

/* This is a global array of translation strings on front-end */

global $trawell_translate;

$trawell_translate = array(
	'newer_entries' => array('text' => esc_html__('Newer Entries', 'trawell'), 'desc' => 'Pagination (prev/next) link text'),
	'older_entries' => array('text' => esc_html__('Older Entries', 'trawell'), 'desc' => 'Pagination (prev/next) link text'),
	'load_more' => array('text' => esc_html__('Load More', 'trawell'), 'desc' => 'Pagination (load more) link text'),
	'previous_posts' => array('text' => esc_html__('Previous', 'trawell'), 'desc' => 'Pagination (numeric) link text'),
	'next_posts' => array('text' => esc_html__('Next', 'trawell'), 'desc' => 'Pagination (numeric) link text'),
	'previous_post' => array('text' => esc_html__('Previous article', 'trawell'), 'desc' => 'Previous post label on sticky bottom bar for single posts'),
	'next_post' => array('text' => esc_html__('Next article', 'trawell'), 'desc' => 'Next post label on sticky bottom bar for single posts'),
    'view_blog' => array('text' => esc_html__('All stories', 'trawell'), 'desc' => 'CTA button label below posts on home page'),
	'category' => array('text' => esc_html__('Category - ', 'trawell'), 'desc' => 'Category archive title prefix', 'default' => '-1'),
	'tag' => array('text' => esc_html__('Tag - ', 'trawell'), 'desc' => 'Tag archive title prefix'),
	'author' => array('text' => esc_html__('Author - ', 'trawell'), 'desc' => 'Author archive title prefix'),
	'archive' => array('text' => esc_html__('Archive - ', 'trawell'), 'desc' => 'Archive title prefix'),
	'search_results_for' => array('text' => esc_html__('Search results for - ', 'trawell'), 'desc' => 'Title for search results template'),
	'search_placeholder' => array('text' => esc_html__('Type here to search...', 'trawell'), 'desc' => 'Search placeholder text'),
	'search_button' => array('text' => esc_html__('Search', 'trawell'), 'desc' => 'Search button text'),
	'min_read' => array( 'text' => esc_html__( 'min read', 'trawell' ), 'desc' => 'Used in post meta data (reading time)' ),
    'about_the_author' => array('text' => esc_html__('About the author', 'trawell'), 'desc' => 'Author box on single title'),
    'share' => array('text' => esc_html__('Share this article', 'trawell'), 'desc' => 'Share buttons label'),
    'written_by' => array('text' => esc_html__('Written by', 'trawell'), 'desc' => 'Line before authors name'),
    'tagged_with' => array('text' => esc_html__('Tags', 'trawell'), 'desc' => 'Tags label'),
    'view_all' => array('text' => esc_html__('View stories', 'trawell'), 'desc' => 'View all posts link text in author box'),
	'instagram_follow' => array('text' => esc_html__('Follow', 'trawell'), 'desc' => 'Instagram pre-footer "follow" link label'),
    'related_posts' => array('text' => esc_html__('Related posts', 'trawell'), 'desc' => 'Title of the Related box on single post'),
    'leave_a_reply' => array('text' => esc_html__('Leave a reply', 'trawell'), 'desc' => 'Title of comments box'),
    'comment_reply' => array('text' => esc_html__('Reply', 'trawell'), 'desc' => 'Comment reply label'),
    'comment_submit' => array('text' => esc_html__('Submit Comment', 'trawell'), 'desc' => 'Comment form submit button label'),
    'comment_text' => array('text' => esc_html__('Comment', 'trawell'), 'desc' => 'Comment form text area label'),
    'comment_email' => array('text' => esc_html__('Email', 'trawell'), 'desc' => 'Comment form email label'),
    'comment_name' => array('text' => esc_html__('Name', 'trawell'), 'desc' => 'Comment form name label'),
    'comment_website' => array('text' => esc_html__('Website', 'trawell'), 'desc' => 'Comment form website label'),
    'comment_cancel_reply' => array('text' => esc_html__('Cancel reply', 'trawell'), 'desc' => 'Comment cancel reply label'),
    'no_comments' => array( 'text' => esc_html__( 'Add comment', 'trawell' ), 'desc' => 'Comment meta data (if zero comments)' ),
    'one_comment' => array( 'text' => esc_html__( '1 comment', 'trawell' ), 'desc' => 'Comment meta data (if 1 comment)' ),
    'multiple_comments' => array( 'text' => esc_html__( '% comments', 'trawell' ), 'desc' => 'Comment meta data (if more than 1 comments)' ),
    'articles' => array('text' => esc_html__('articles', 'trawell'), 'desc' => 'Number of posts/articles label for categories'),
    'home_cover_title' => array('text' => esc_html__('Where will you go next?', 'trawell'), 'desc' => 'Home page cover title', 'hidden' => true),
    'home_cover_text' => array('text' => esc_html__('Welcome to Trawell, a WordPress theme carefully crafted for travelers and adventurers. Pack your bags, hit the road and don\'t forget to write down all of your amazing stories!', 'trawell'), 'desc' => 'Home page cover description', 'hidden' => true),
	'home_cover_button_1_text' => array('text' => esc_html__('Button 1', 'trawell'), 'desc' => 'Home page cover button 1 text', 'hidden' => true),
	'home_cover_button_2_text' => array('text' => esc_html__('Button 2', 'trawell'), 'desc' => 'Home page cover button 2 text', 'hidden' => true),
	'home_counters_title' => array('text' => esc_html__('The Numbers', 'trawell'), 'desc' => 'Home page numbers section title', 'hidden' => true),
	'home_counter_1_title' => array('text' => esc_html__('Continents visited', 'trawell'), 'desc' => 'Home page numbers item 1 text', 'hidden' => true),
	'home_counter_2_title' => array('text' => esc_html__('Countries visited', 'trawell'), 'desc' => 'Home page numbers item 2 text', 'hidden' => true),
	'home_counter_3_title' => array('text' => esc_html__('Miles traveled', 'trawell'), 'desc' => 'Home page numbers item 3 text', 'hidden' => true),
	'home_counter_4_title' => array('text' => esc_html__('Days traveling', 'trawell'), 'desc' => 'Home page numbers item 4 text', 'hidden' => true),
	'home_counter_5_title' => array('text' => esc_html__('Stories written', 'trawell'), 'desc' => 'Home page numbers item 5 text', 'hidden' => true),
	'home_posts_title' => array('text' => esc_html__('Where I\'ve been', 'trawell'), 'desc' => 'Home page posts section title', 'hidden' => true),
	'home_categories_title' => array('text' => esc_html__('Destinations', 'trawell'), 'desc' => 'Home page categories section title', 'hidden' => true),
	'home_about_title' => array('text' => esc_html__('About me', 'trawell'), 'desc' => 'Home page about me section title', 'hidden' => true),
	'home_about_text' => array('text' => esc_html__('Something about me...', 'trawell'), 'desc' => 'Home page about me section text', 'hidden' => true),
	'home_about_button_1_text' => array('text' => esc_html__('Read my blog', 'trawell'), 'desc' => 'Home page about me section first button text', 'hidden' => true),
	'home_about_button_2_text' => array('text' => esc_html__('Learn more', 'trawell'), 'desc' => 'Home page about me section second button text', 'hidden' => true),
	'home_as_seen_in_title' => array('text' => esc_html__('As seen in', 'trawell'), 'desc' => 'Home page as seen in section title', 'hidden' => true),
	'home_custom_content_title' => array('text' => esc_html__('Custom content title', 'trawell'), 'desc' => 'Home page custom content section title', 'hidden' => true),
	'home_custom_content' => array('text' => esc_html__('This is the place for custom content...', 'trawell'), 'desc' => 'Home page custom content', 'hidden' => true),
    'close' => array('text' => esc_html__('Close', 'trawell'), 'desc' => 'Close text for responsive sidebar'),
    'menu' => array('text' => esc_html__('Menu', 'trawell'), 'desc' => 'Label text for responsive navigation'),
	'content_none' => array('text' => esc_html__('Sorry, there is no content found on this page. Feel free to contact the website administrator regarding this issue.', 'trawell'), 'desc' => 'Message when there are no posts on archive pages. i.e an empty Category'),
	'404_title' => array('text' => esc_html__('Page not found', 'trawell'), 'desc' => '404 page title'),
	'404_text' => array('text' => esc_html__('The page that you are looking for does not exist on this website. You may have accidentally mistype the page address, or followed an expired link. Anyway, we will help you get back on track. Why not try to search for the page you were looking for:', 'trawell'), 'desc' => '404 page text'),
	'more' => array('text' => esc_html__('More', 'trawell'), 'desc' => 'More link text in responsive menu'),
	'cart' => array('text' => esc_html__('Cart', 'trawell'), 'desc' => 'Woocommrece Cart'),
);

?>